#!/bin/zsh

CMDNAME=`basename $0`

current_dir=""
split_opts=""

while getopts dhvPp:l:t:b: OPT
do
    case $OPT in
        "d" | "h" | "v" | "P" ) split_opts="$split_opts -$OPT";;
        "p" | "l" | "t" ) split_opts="$split_opts -$OPT $OPTARG";;
        "b" ) current_dir=$OPTARG;;
          * ) echo "Usage: $CMDNAME [-dhvP] [-p percentage|-l size] [-t target-pane] [command]" 1>&2
              exit 1;;
    esac
done

shift `expr $OPTIND - 1`

spawn_command=$@

if [ -z $TMUX ]; then
    `echo -n $spawn_command`
elif [ -z $current_dir ]; then
    tmux split-window `echo -n $split_opts` "$CMDNAME -b $PWD $spawn_command"
else
    cd $current_dir
    `echo -n $spawn_command`
fi

