#!/bin/zsh

CMDNAME=`basename $0`

tvim_path=""
split_opts=""

while getopts dhvPp:l:t:b: OPT
do
    case $OPT in
        "d" | "h" | "v" | "P" ) split_opts="$split_opts -$OPT";;
        "p" | "l" | "t" ) split_opts="$split_opts -$OPT $OPTARG";;
        "b" ) tvim_path=$OPTARG;;
          * ) echo "Usage: $CMDNAME [-dhvP] [-p percentage|-l size] [-t target-pane] [vim-arguments]" 1>&2
              exit 1;;
    esac
done

shift `expr $OPTIND - 1`

vim_args=$@

if [ -z $TMUX ]; then
    vim $vim_args
elif [ -z $tvim_path ]; then
    tmux split-window `echo -n $split_opts` "tvim -b $PWD $vim_args"
else
    cd $tvim_path
    vim $vim_args
fi

